/*
======================================================================
Copyright (c) 2026 Jeremie W
SPDX-License-Identifier: Apache-2.0

File Name:  kwe_sine.v
Author:     Jeremie W (willab.ch)
Brief:      Compute the sine from input angle
======================================================================

Only the first quadrant is stored; the other three are generated by index mirroring and
output negation.

LUT[i] = round(127 * sin((i + 0.5) * pi/64)),  i = 0..31

| Quadrant `angle[6:5]` | Value |
|---|---|
| 00 | `+LUT[idx]` |
| 01 | `+LUT[31-idx]` |
| 10 | `-LUT[idx]` |
| 11 | `-LUT[31-idx]` |

The half-step centring (`i + 0.5`) makes the mirror exact without needing a stored zero or
a 33rd entry.

**32 entries is the right size, and a larger table would be wasted area.** The LUT's
worst-case quantization step is 7 LSB. The intrinsic frame-to-frame step from updating at
only 50 Hz is 8 LSB at the nominal 2 s period. The LUT is therefore *already* below the
dominant artifact — doubling it to 64 entries would halve an error that is not what you
are seeing. */

module kwe_sine (
    input  wire        [6:0] angle,   // unsigned 0..127, one full turn
    output wire signed [8:0] sine     // -127 .. +127
);

    wire [1:0] quadrant;
    wire [4:0] lut_idx;
    wire [7:0] lut_sine;

    // see header
    assign quadrant = angle[6:5];
    assign lut_idx  = quadrant[0] ? (5'd31 - angle[4:0]) : angle[4:0];

    kwe_sine_lut my_lut_instance (
        .idx(lut_idx),   
        .val(lut_sine)
    );

    assign sine = quadrant[1]   ? -$signed({1'b0, lut_sine}) 
                                : $signed({1'b0, lut_sine});


endmodule