/*
======================================================================
Copyright (c) 2026 Jeremie W
SPDX-License-Identifier: Apache-2.0

File Name:  kwe_sine_lut.v
Author:     Jeremie W (willab.ch)
Brief:      store the sine lut. Only first quadrant is necessary.
            The other three are generated by index mirroring and
            output negation.
======================================================================

LUT[i] = round(127 * sin((i + 0.5) * pi/64)),  i = 0..31

    3   9  16  22  28  34  40  46      // idx  0- 7
   51  57  63  68  73  78  83  88      // idx  8-15
   92  96 100 104 107 111 113 116      // idx 16-23
  118 121 122 124 125 126 127 127      // idx 24-31

*/

`default_nettype none

module kwe_sine_lut (
    input  wire [4:0] idx,
    output reg [7:0] val      // LUT table from PRD §6.4
);

    always @(*) begin
        case (idx)
            // idx  0-7
            5'd0:  val = 8'd3;
            5'd1:  val = 8'd9;
            5'd2:  val = 8'd16;
            5'd3:  val = 8'd22;
            5'd4:  val = 8'd28;
            5'd5:  val = 8'd34;
            5'd6:  val = 8'd40;
            5'd7:  val = 8'd46;
            
            // idx  8-15
            5'd8:  val = 8'd51;
            5'd9:  val = 8'd57;
            5'd10: val = 8'd63;
            5'd11: val = 8'd68;
            5'd12: val = 8'd73;
            5'd13: val = 8'd78;
            5'd14: val = 8'd83;
            5'd15: val = 8'd88;
            
            // idx  16-23
            5'd16: val = 8'd92;
            5'd17: val = 8'd96;
            5'd18: val = 8'd100;
            5'd19: val = 8'd104;
            5'd20: val = 8'd107;
            5'd21: val = 8'd111;
            5'd22: val = 8'd113;
            5'd23: val = 8'd116;
            
            // idx  24-31
            5'd24: val = 8'd118;
            5'd25: val = 8'd121;
            5'd26: val = 8'd122;
            5'd27: val = 8'd124;
            5'd28: val = 8'd125;
            5'd29: val = 8'd126;
            5'd30: val = 8'd127;
            5'd31: val = 8'd127;
            
            // Fallback for safety
            default: val = 8'd0;
        endcase
    end

endmodule